# Generated by Django 4.2.9 on 2026-01-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, default='Gym enthusiast ready to crush goals!')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
