# Generated by Django 3.2.25 on 2026-01-21 21:37

from django.db import migrations, models
import djongo.models.fields
import exercises.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullRoutineVideo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(choices=[('PURPLE', 'Púrpura'), ('RED', 'Rojo'), ('BLUE', 'Azul'), ('SKIN', 'Piel')], max_length=20)),
                ('hex_color', models.CharField(max_length=7)),
                ('description', models.TextField(blank=True)),
                ('subgroups', djongo.models.fields.ArrayField(default=list, model_container=exercises.models.SubGroup)),
            ],
        ),
    ]
