# Generated by Django 3.2.25 on 2026-01-21 21:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='routines.routine')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup_name', models.CharField(max_length=100)),
                ('exercise_name', models.CharField(max_length=200)),
                ('exercise_id', models.CharField(max_length=100)),
                ('target_sets', models.IntegerField(default=4)),
                ('target_reps', models.IntegerField(default=12)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routines.routinegroup')),
            ],
            options={
                'ordering': ['subgroup_name', 'exercise_name'],
            },
        ),
    ]
