import os
import django
import uuid
from django.utils import timezone

# Configuración de Django para script standalone
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "app.settings")
django.setup()

# Ajusta el import según dónde creaste el modelo arriba (ej: workouts.models o app.models)
from workouts.models import WorkoutCommand

# EL UUID DETERMINISTA (La clave para vincular todo)
ADMIN_UUID = "00000000-0000-0000-0000-000000000001"

def seed():
    # Verificamos si ya existen comandos para este usuario
    if WorkoutCommand.objects.filter(user_id=ADMIN_UUID).exists():
        print(f"⚠️  Command data for {ADMIN_UUID} already exists.")
        return

    print(f"🌱 Seeding Workout Command for Admin ({ADMIN_UUID})...")
    
    WorkoutCommand.objects.create(
        user_id=ADMIN_UUID, # <- El vínculo crítico
        name="Admin First Session",
        notes="Generated by seed script directly in Command Service",
        status="completed",
        started_at=timezone.now()
    )
    print("✅ Workout Command seeded successfully.")

if __name__ == "__main__":
    seed()